name: Terraform Staging

on:
  push:
    branches:
      - main
    paths:
      - "modules/**"
      - "envs/staging/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_STAGING }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6


      - name: Terraform Init
        run: terraform init
        working-directory: envs/staging

      # - name: Terraform Plan
      #   run: |
      #     terraform plan \
      #     -target=module.network \
      #     -target=module.iam \
      #     -target=module.rds \
      #     -target=module.ec2 \
      #     -target=module.alb
      #   working-directory: envs/staging
      #   env:
      #     TF_VAR_db_password: ${{ secrets.DB_PASSWORD_STAGING }}


#  # Step 1: Apply dependencies
#       - name: Terraform Apply Dependencies
#         run: |
#           terraform apply -auto-approve \
#           -target=module.network \
#           -target=module.iam \
#           -target=module.rds \
#           -target=module.ec2 \
#           -target=module.alb 
#         working-directory: envs/staging
#         env:
#           TF_VAR_db_password: ${{ secrets.DB_PASSWORD_STAGING }}

#  # Step 2: Apply CloudWatch
#       - name: Terraform Apply CloudWatch
#         run: terraform apply -auto-approve
#         working-directory: envs/staging
#         env:
#           TF_VAR_db_password: ${{ secrets.DB_PASSWORD_STAGING }}


      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: envs/staging
        env:
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD_STAGING }}
    #